# Generated by Django 3.0.3 on 2020-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=50)),
                ('Bookpages', models.IntegerField()),
                ('Bookprice', models.IntegerField()),
            ],
        ),
    ]
